---
title: "ggplot1"
author: "Keyi Wang"
date: "10/7/2019"
output: github_document
---

```{r setup,include=FALSE}
library(tidyverse)
library(ggridges)
```

#### create the weather data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## create a ggplot
```{r}
ggplot(weather_df,aes(x = tmin,y = tmax)) +
  geom_point()

```

alternate way of making this plot
```{r}
weather_df %>%
  ggplot(aes(x = tmin,y = tmax)) + geom_point()

weather_df %>% filter(name == "CentralPark_NY")

##adding color
weather_df %>%
  ggplot(aes(x = tmin,y = tmax)) + 
  geom_point(aes(color = name),alpha = 0.4) 
##alpha for transparency  , different color for different location
```

why do aes positions matter?

first
```{r}
weather_df %>%
  ggplot(aes(x = tmin,y = tmax)) + 
  geom_point(aes(color = name),alpha = 0.4) +
  geom_smooth(se = FALSE)

```
vs
```{r}
weather_df %>%
  ggplot(aes(x = tmin,y = tmax,color = name)) + ## color now is applying in everywehre
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE)
```


facet--seperate it into three panels based on location
```{r}
weather_df %>%
  ggplot(aes(x = tmin,y = tmax,color = name)) +
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE)  +
  facet_grid(~name)

```


```{r}
weather_df %>%
  ggplot(aes(x= date, y=tmax,color = name))+
  geom_point(aes(size=prcp)) + ###include precp information
  geom_smooth()

```

```{r}
weather_df %>%
  ggplot(aes(x= date, y=tmax,color = name))+
  geom_point(aes(size=prcp), alpha = 0.35) + ###include precp information
  geom_smooth(size=2)
```

2d density
```{r}
## install.package("hexbin")
weather_df %>%
  ggplot(aes(x= tmin, y=tmax)) +
  geom_bin2d()
  

```

## more kinds of plots!
```{r}
weather_df %>%
  ggplot(aes(x = tmax,fill = name)) +
  geom_histogram(position = "dodge")


weather_df %>%
  ggplot(aes(x = tmax,fill = name)) +
  geom_histogram()+
  facet_grid(~name)

### density plots
weather_df %>%
  ggplot(aes(x = tmax,fill = name)) +
  geom_density(alpha = 0.3)

```


```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```

ridge plots
```{r}
weather_df %>%
  ggplot(aes(x = tmax,y = name)) +
  geom_density_ridges()
```

saving plots
```{r}
ggplot_ridge_temp =
  weather_df %>%
  ggplot(aes(x = tmax,y = name)) +
  geom_density_ridges()
ggsave("ggplot_temp_ridge.pdf",ggplot_ridge_temp)
```










